Repository GeodeCompany/geode-cracker-react, pull requests merged in 2023-01, with the labels that each got.

#32 feature: add audio to crack interaction
  geode-cracker/public/sound/crack_audio_geode_crack.wav
  geode-cracker/public/sound/crack_audio_geode_open.wav
  geode-cracker/public/sound/crack_audio_geode_place.wav
  geode-cracker/src/Crack/Crack.js
Labels: feature

#33 fix: settings popup language and polish.js action text
  geode-cracker/src/Polish/Polish.js
  geode-cracker/src/Settings/Components/SettingsConfirmation.js
  geode-cracker/src/Settings/Settings.js
Labels: feature, Fix

#34 tweak: update json
  geode-cracker/src/Polish/Polish.js
  geode-cracker/src/data_EN.json
  geode-cracker/src/data_NL.json
Labels: tweak

#35 tweak(collection.scss): add page centering
  geode-cracker/src/Collection/Collection.scss
Labels: tweak

#38 tweak(crack.js): iteration 2
  geode-cracker/src/Crack/Crack.js
  geode-cracker/src/index.scss
Labels: tweak

#39 feat(collection.js):add back button
  geode-cracker/src/Collection/Collection.js
  geode-cracker/src/Collection/Collection.scss
  geode-cracker/src/Settings/Settings.scss
Labels: feature, tweak
